<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function taskToDo($date)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Task t WHERE t.toBeFinishedAt < :date'
            )
            ->setParameter('date', $date)
            ->getResult();
    }
}
